### ISSUE TITLE
关于这个项目的疑问

### ISSUE THREAD

**Issue by liudonghua123** [kinlog/visualgo#35]
这个项目和 http://visualgo.net 有些类似，是参考其设计自己实现的还是在它的可能开源代码上 例如 https://github.com/Visualgo-Internalization/visualgo 或者 https://github.com/DTMonkey/visualgo 做的呢？

**Comment by kinlog** [comment]
本项目的前端页面设计参考了该项目，但二者作图方式不同，前者是canvas画图，后者是svg动画。
